name: Install OpenSSL
description: Install and setup OpenSSL for linking and building test application
inputs:
  version:
    description: The desired OpenSSL version to install
    required: false
    default: "openssl-3.2.0"
runs:
  using: composite
  steps:
    - name: Cache OpenSSL
      id: cache-openssl
      uses: actions/cache@v3
      with:
        path: openssl-${{ inputs.version }}
        key: ${{ runner.name }}-${{ runner.os }}-${{ runner.arch }}-${{ job.container.id }}-openssl-${{ inputs.version }}

    - uses: ilammy/setup-nasm@v1
    - if: steps.cache-openssl.outputs.cache-hit != 'true'
      shell: powershell
      run: |
        Invoke-WebRequest -OutFile ${{ inputs.version }}.tar.gz -Uri https://github.com/openssl/openssl/archive/refs/tags/${{ inputs.version }}.tar.gz
    - if: steps.cache-openssl.outputs.cache-hit != 'true'
      shell: cmd
      run: |
        tar -zxf ${{ inputs.version }}.tar.gz
        cd openssl-${{ inputs.version }}
        perl Configure VC-WIN64A --prefix=${{ github.workspace }}\openssl no-tests
        nmake
        
    - uses: ilammy/msvc-dev-cmd@v1
    - shell: bash
      run: |
        cd openssl-${{ inputs.version }}
        nmake install
        echo "OPENSSL_ROOT_DIR=${{ github.workspace }}/openssl" >> "$GITHUB_ENV"
        echo "OpenSSL_ROOT=${{ github.workspace }}/openssl" >> "$GITHUB_ENV"
