name: Install LibreSSL
description: Install and setup GTest for linking and building test application
inputs:
  version:
    description: The desired LibreSSL version to install
    required: false
    default: '3.3.0'
runs:
  using: composite
  steps:
  - run: wget https://ftp.openbsd.org/pub/OpenBSD/LibreSSL/libressl-${{ inputs.version }}.tar.gz -P /tmp
    shell: bash
  - run: tar -zxf /tmp/libressl-${{ inputs.version }}.tar.gz -C /tmp
    shell: bash
  - run: cd /tmp/libressl-${{ inputs.version }}
    shell: bash
  - run: cmake -B/tmp/libressl-${{ inputs.version }} -S/tmp/libressl-${{ inputs.version }} -DLIBRESSL_APPS=OFF -DLIBRESSL_TESTS=OFF
    shell: bash
  - run: cmake --build /tmp/libressl-${{ inputs.version }}
    shell: bash
  - run: sudo cmake --install /tmp/libressl-${{ inputs.version }}
    shell: bash
