name: Install OpenSSL
description: Install and setup OpenSSL for linking and building test application
inputs:
  version:
    description: The desired OpenSSL version to install
    required: false
    default: "openssl-3.2.0"
runs:
  using: composite
  steps:
    - if: runner.os == 'Windows'
      uses: ./github/actions/install/openssl/windows
      with:
        version: ${{ inputs.version }}

    - if: runner.os == 'Linux' 
      uses: ./github/actions/install/openssl/linux
      with:
        version: ${{ inputs.version }}

