name: LibreSSL CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        libressl: ["3.3.0"]
    steps:
    - uses: actions/checkout@v2
    - name: install cmake
      uses: lukka/get-cmake@latest
    - name: install gtest
      uses: ./.github/actions/install-gtest
    - name: install libressl
      uses: ./.github/actions/install-libressl
      with:
      - version: ${{ matrix.libressl }}

    - name: configure
      run: cmake . -DJWT_BUILD_TESTS=ON -DJWT_SSL_LIBRARY:STRING=LibreSSL

    - name: make
      run: make

    - name: test
      run: ./tests/jwt-cpp-test

    - name: badge success
      if: ${{ success() }}
      run: |
        echo '{ "schemaVersion": 1, "label": "${{ matrix.libressl }}", "message": "Passing", "color": "brightgreen" }' > badges/libressl/${{ matrix.libressl }}/shields.json

    - name: badge failure
      if: ${{ !success() }}
      run: |
        echo '{ "schemaVersion": 1, "label": "${{ matrix.libressl }}", "message": "Failing", "color": "red" }' > badges/libressl/${{ matrix.libressl }}/shields.json

    - name: badge publish
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_branch: badges
        publish_dir: ./badges
