name: SSL Compatibility CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  openssl:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, ubuntu-latest]
        openssl:
          - "3.3.0"
          - "3.2.1"
          - "3.1.5"
          - "3.0.13"
          - "1.1.1w"
          - "1.1.0i" # Do not bump, there's a broken in the autoconfig script and it's not maintained
          - "1.0.2u"
          - "1.0.1u"
        exclude:
        # The older version of OpenSSL were less cross-platform friendly, the Windows build had a seperate set of build
        # scripts but it's just a pain to support them, see the failed attempt:
        # https://github.com/prince-chrismc/jwt-cpp/pull/35/commits/e4948d2e1b7ec03896f80669fab6f9a2edf7ea63
          - os: windows-latest
            openssl: "1.1.0i"
          - os: windows-latest
            openssl: "1.0.2u"
          - os: windows-latest
            openssl: "1.0.1u"
    name: OpenSSL ${{ matrix.openssl }} - ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: lukka/get-cmake@latest
      - uses: ./.github/actions/install/openssl
        with:
          version: ${{ fromJson('{"3.3.0":"openssl-3.3.0","3.2.1":"openssl-3.2.1","3.1.5":"openssl-3.1.5","3.0.13":"openssl-3.0.13","1.1.1w":"OpenSSL_1_1_1w","1.1.0i":"OpenSSL_1_1_0i","1.0.2u":"OpenSSL_1_0_2u","1.0.1u":"OpenSSL_1_0_1u"}')[matrix.openssl] }}
      - name: configure
        run: cmake --preset unit-tests
      - run: cmake --build --preset unit-tests
      - name: test
        run: ctest --preset unit-tests

      - if: github.event_name == 'push' && matrix.os == 'ubuntu-latest' && always()
        uses: ./.github/actions/badge
        with:
          category: openssl
          label: ${{ matrix.openssl }}

  openssl-no-deprecated:
    runs-on: ubuntu-latest
    name: OpenSSL 3.0 No Deprecated
    steps:
      - uses: actions/checkout@v4
      - uses: lukka/get-cmake@latest
      - uses: ./.github/actions/install/gtest
      - uses: ./.github/actions/install/openssl
        with:
          version: "openssl-3.3.0"

      - name: configure
        run: cmake --preset unit-tests -DCMAKE_CXX_FLAGS="-DOPENSSL_NO_DEPRECATED=1" -DCMAKE_C_FLAGS="-DOPENSSL_NO_DEPRECATED=1"
      - run: cmake --build --preset unit-tests
      - name: test
        run: ctest --preset unit-tests

  libressl:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        libressl: ["3.9.1", "3.8.2", "3.7.3"]
    name: LibreSSL ${{ matrix.libressl }}
    steps:
      - uses: actions/checkout@v4
      - uses: lukka/get-cmake@latest
      - uses: ./.github/actions/install/gtest
      - uses: ./.github/actions/install/libressl
        with:
          version: ${{ matrix.libressl }}

      - name: configure
        run: cmake --preset unit-tests -DJWT_SSL_LIBRARY:STRING=LibreSSL
      - run: cmake --build --preset unit-tests
      - name: test
        run: ctest --preset unit-tests

      - if: github.event_name == 'push' && always()
        uses: ./.github/actions/badge
        with:
          category: libressl
          label: ${{ matrix.libressl }}

  wolfssl:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        wolfssl:
          - { ref: "v5.6.6-stable", name: "5.6.6"}
          - { ref: "v5.5.4-stable", name: "5.5.4" }
          - { ref: "v5.7.0-stable", name: "5.7.0"}
    name: wolfSSL ${{ matrix.wolfssl.name }}
    steps:
      - uses: actions/checkout@v4
      - uses: lukka/get-cmake@latest
      - uses: ./.github/actions/install/gtest
      - uses: ./.github/actions/install/wolfssl
        with:
          version: ${{ matrix.wolfssl.ref }}

      - name: configure
        run: cmake --preset unit-tests -DJWT_SSL_LIBRARY:STRING=wolfSSL
      - run: cmake --build --preset unit-tests
      - name: test
        run: ctest --preset unit-tests

      - if: github.event_name == 'push' && always()
        uses: ./.github/actions/badge
        with:
          category: wolfssl
          label: ${{ matrix.wolfssl.name }}
